development:
  site: howaboutwe
  use_ssl: true
  rooms:
  - dbtest
  api_key: 3f333b843e500d6e5dd087185b7c10e857b52fe2
  nickname: peat
  fullname: peat
  password: howaboutwe123
  enable_plugins:
    - trivia
    - peat
    - rolloff
production:
  site: howaboutwe
  use_ssl: true
  rooms:
  - overalls
  api_key: 3f333b843e500d6e5dd087185b7c10e857b52fe2
  nickname: peat
  fullname: peat
  password: howaboutwe123
  enable_plugins:
    - trivia
    - peat
    - rolloff

